
--1. Conocer los datos de los empleados que tengan más de 15 años en servicio y
--ordenar de mayor a menor con respecto a los años de laborar.
SELECT * FROM EMPLEADO WHERE EXTRACT(YEAR FROM FECHA_INGRESO) < '2006' ORDER BY FECHA_INGRESO DESC;

--2. Conocer el nombre, edad, puesto y la fecha en la que inició a trabajar cada uno de
--los empleados, ordenar ascendemente por nombre y descendemente por la fecha
--de ingreso.
SELECT NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,AGE(FECHA_NACIMIENTO) EDAD,ROL,FECHA_INGRESO
FROM EMPLEADO ORDER BY NOMBRES ASC, FECHA_INGRESO DESC;

--3. Conocer el vivero con mayor cantidad de plantas a la venta.
SELECT NOMBRE_VIVERO FROM PERTENECE WHERE CANTIDAD = (SELECT MAX(CANTIDAD) FROM PERTENECE);

--4. Conocer los nombres de los empleados asociados con la mayor cantidad de ven-
--tas por día de cada uno de los viveros.

SELECT * FROM
(SELECT ID_EMPLEADO,NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRE_VIVERO,FECHA,COUNT(ID_VENTA) TOTAL_VENTAS
FROM EMPLEADO NATURAL JOIN
 (SELECT ID_EMPLEADO_COBRAR ID_EMPLEADO,FECHA,ID_VENTA FROM VENTA_FISICA) D
GROUP BY ID_EMPLEADO,NOMBRE_VIVERO,FECHA
UNION
SELECT ID_EMPLEADO,NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRE_VIVERO,FECHA,COUNT(NUMERO_SEGUIMIENTO) TOTAL_VENTAS
FROM EMPLEADO NATURAL JOIN
 (SELECT NUMERO_SEGUIMIENTO,FECHA,ID_EMPLEADO_COBRAR ID_EMPLEADO FROM VENTA_ONLINE) C
GROUP BY ID_EMPLEADO,NOMBRE_VIVERO,FECHA) X
NATURAL JOIN
(SELECT FECHA,MAX(TOTAL_VENTAS) TOTAL_VENTAS,NOMBRE_VIVERO FROM
((SELECT FECHA,COUNT(ID_VENTA) TOTAL_VENTAS, NOMBRE_VIVERO
FROM EMPLEADO NATURAL JOIN
 (SELECT ID_EMPLEADO_COBRAR ID_EMPLEADO,FECHA,ID_VENTA FROM VENTA_FISICA) D
GROUP BY ID_EMPLEADO,FECHA)
 UNION
(SELECT FECHA,COUNT(NUMERO_SEGUIMIENTO) TOTAL_VENTAS, NOMBRE_VIVERO
FROM EMPLEADO NATURAL JOIN
 (SELECT ID_EMPLEADO_COBRAR ID_EMPLEADO,FECHA,NUMERO_SEGUIMIENTO FROM VENTA_ONLINE) D
GROUP BY ID_EMPLEADO,FECHA))
 E GROUP BY FECHA,NOMBRE_VIVERO) Y;
 
--5. Conocer la cantidad de ventas y la suma total de estas ventas por día de cada uno
--de los viveros

SELECT * FROM
((SELECT FECHA,NOMBRE_VIVERO, COUNT(ID_VENTA) CANTIDAD_VENTAS FROM VENTA_FISICA GROUP BY FECHA,NOMBRE_VIVERO)
UNION
SELECT FECHA,NOMBRE_VIVERO,COUNT(NUMERO_SEGUIMIENTO) CANTIDAD_VENTAS FROM EMPLEADO NATURAL JOIN
(SELECT NUMERO_SEGUIMIENTO,FECHA,ID_EMPLEADO_COBRAR ID_EMPLEADO FROM VENTA_ONLINE) A GROUP BY FECHA,NOMBRE_VIVERO) C
NATURAL JOIN
(SELECT NOMBRE_VIVERO, SUM(CANTIDAD_VENTAS) TOTAL FROM
((SELECT FECHA,NOMBRE_VIVERO, COUNT(ID_VENTA) CANTIDAD_VENTAS FROM VENTA_FISICA GROUP BY FECHA,NOMBRE_VIVERO)
UNION
SELECT FECHA,NOMBRE_VIVERO,COUNT(NUMERO_SEGUIMIENTO) CANTIDAD_VENTAS FROM EMPLEADO NATURAL JOIN
(SELECT NUMERO_SEGUIMIENTO,FECHA,ID_EMPLEADO_COBRAR ID_EMPLEADO FROM VENTA_ONLINE) A GROUP BY FECHA,NOMBRE_VIVERO) B
GROUP BY NOMBRE_VIVERO) D;

-- 6. Conocer la forma de pago fisica más recurrente.
SELECT NOMBRE_FORMA_PAGO FROM
(SELECT NOMBRE_FORMA_PAGO, COUNT(NOMBRE_FORMA_PAGO) APARICIONES
	FROM FORMA_PAGO_FISICA GROUP BY NOMBRE_FORMA_PAGO) C WHERE APARICIONES =
	(SELECT MAX(APARICIONES) FROM (
	SELECT NOMBRE_FORMA_PAGO, COUNT(NOMBRE_FORMA_PAGO) APARICIONES
	FROM FORMA_PAGO_FISICA GROUP BY NOMBRE_FORMA_PAGO) A);

--7. Conocer la venta con mayor cantidad de plantas y en que vivero fue realizada.

SELECT * FROM
(SELECT ID_VENTA,NOMBRE_VIVERO, FECHA, NUMERO_PRODUCTOS, 'Fisica' TIPO FROM VENTA_FISICA
UNION
SELECT NUMERO_SEGUIMIENTO ID_VENTA,NOMBRE_VIVERO,FECHA,NUMERO_PRODUCTOS, 'Online' TIPO FROM EMPLEADO NATURAL JOIN
(SELECT NUMERO_SEGUIMIENTO,FECHA,NUMERO_PRODUCTOS,ID_EMPLEADO_COBRAR ID_EMPLEADO FROM VENTA_ONLINE) C) A
WHERE NUMERO_PRODUCTOS =
(SELECT MAX(NUMERO_PRODUCTOS) FROM
(SELECT NUMERO_SEGUIMIENTO ID_VENTA, FECHA, NUMERO_PRODUCTOS FROM VENTA_ONLINE
UNION
SELECT ID_VENTA, FECHA, NUMERO_PRODUCTOS FROM VENTA_FISICA) B);
